// Compile the displayed study snippets, then compare key designs to slow independent oracles.
const fs=require('node:fs'),cp=require('node:child_process'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const cs=window.CHAPTERS, get=id=>cs.find(c=>c.id===id).code;
const snippets={
 'stl-performance':()=>{const s=get('stl-performance').split('// Dijkstra')[0];return s+'\nvoid test(){assert(kthLargest({8,2,9,1,7},2)==8);assert(kthLargest({4,9,9,1},2)==9);assert(kthLargest({-3},1)==-3);}';},
 'grid-search':()=>get('grid-search')+'\nvoid test(){assert(shortestPath({"11"},0,0,0,1)==1);assert(shortestPath({"1110","0101","1111"},0,0,2,3)==5);assert(shortestPath({"1"},0,0,0,0)==0);assert(shortestPath({"0"},0,0,0,0)==-1);assert(shortestPath({"10","01"},0,0,1,1)==-1);}',
 'graph-model':()=> 'void test(){int n=3,u=0,v=2,start=0;long long w=4;'+get('graph-model')+'\nassert(seen[2]&&!seen[1]);}',
 'shortest-variants':()=>{const [decl,loop]=get('shortest-variants').split('// Floyd-Warshall core:');return decl+'\nvoid test(){vector<long long> d;vector<Edge> e={{0,1,4},{0,2,5},{1,2,-3}};assert(bellmanFord(3,0,e,d)&&d[2]==1);e.push_back({2,1,1});assert(!bellmanFord(3,0,e,d));int n=4;vector<vector<long long>> dist(n,vector<long long>(n,INF));for(int i=0;i<n;++i)dist[i][i]=0;dist[0][1]=2;dist[1][2]=1;dist[2][3]=1;'+loop.slice(loop.indexOf('\n'))+'\nassert(dist[0][3]==4&&dist[3][0]==INF);}';},
 'sqrt-decomposition':()=>get('sqrt-decomposition')+`\nvoid test(){mt19937 rng(51);for(int n=1;n<60;++n){vector<long long>a(n);for(auto&x:a)x=int(rng()%101)-50;SqrtMax s(a);for(int z=0;z<80;++z){int i=rng()%n;a[i]=int(rng()%101)-50;s.update(i,a[i]);int l=rng()%n,r=l+1+rng()%(n-l);assert(s.query(l,r)==*max_element(a.begin()+l,a.begin()+r));}}}`,
 'mst':()=>get('mst')+'\nvoid test(){auto a=kruskal(4,{{0,1,1},{1,2,2},{0,2,4},{2,3,3}});assert(a.first==6&&a.second==3);assert(kruskal(4,{{0,1,1}}).second==1);}',
};
Object.assign(snippets,{
 'state-model':()=>get('state-model')+'\nvoid test(){unordered_map<int,int> index={{41,0},{87,1}};assert(lookup(index,87)==1);assert(lookup(index,99)==-1);}',
 'local-update':()=>get('local-update')+'\nvoid test(){vector<int>a={2,5,8,3},sums={7,13,11};updateAdjacent(a,sums,1,10);assert((a==vector<int>{2,10,8,3}));assert((sums==vector<int>{12,18,11}));updateAdjacent(a,sums,0,4);assert((sums==vector<int>{14,18,11}));updateAdjacent(a,sums,3,6);assert((sums==vector<int>{14,18,14}));}',
 'candidate-filter':()=>get('candidate-filter')+'\nvoid test(){vector<int>candidates={0,1,2,3};vector<bool>active={true,false,true,false};assert((filterActive(candidates,active)==vector<int>{0,2}));}',
 'path-algebra':()=>get('path-algebra')+'\nvoid test(){assert(pathQuality({7,4,9})==4);assert(pathQuality({})==numeric_limits<int>::max());}',
 'path-sensitivity':()=>get('path-sensitivity')+'\nvoid test(){vector<int>path={3,8,12};assert(usesEdge(path,8));assert(!usesEdge(path,9));}',
 'resource-state':()=>get('resource-state')+'\nvoid test(){assert(dominates(4,6,5,3));assert(!dominates(4,2,5,3));assert(!dominates(6,6,5,3));}',
 'bitset-cost':()=>get('bitset-cost')+'\nvoid test(){assert(differingBits(0b10101,0b00111)==2);assert(differingBits(0,0)==0);}',
 'ordered-index':()=>get('ordered-index')+'\nvoid test(){set<pair<int,int>> index={{2,7},{4,3}};replaceKey(index,7,2,5);assert(!index.count({2,7})&&index.count({5,7})&&index.begin()->first==4);}',
 'lazy-validity':()=>get('lazy-validity')+'\nvoid test(){assert(validEntry(true,true,4,4));assert(!validEntry(false,true,4,4));assert(!validEntry(true,false,4,4));assert(!validEntry(true,true,3,4));}',
 'order-statistics':()=>get('order-statistics')+'\nvoid test(){vector<int>a={1,2,2,4,8};assert(countLess(a,2)==1);assert(countLess(a,3)==3);assert(countLess(a,0)==0);assert(countLess(a,9)==5);}',
 'dp-patterns':()=>get('dp-patterns')+`\nvoid test(){assert(knapsack01({2,3},{4,5},4)==5);assert(shortestTour({{0}})==0);assert(shortestTour({{-1,1,-1},{-1,-1,1},{1,-1,-1}})==3);mt19937 rng(65);for(int z=0;z<50;++z){int n=2+rng()%6;vector<vector<int>>c(n,vector<int>(n,-1));for(int i=0;i<n;++i)for(int j=0;j<n;++j)if(i!=j&&rng()%4)c[i][j]=rng()%20;vector<int>p;for(int i=1;i<n;++i)p.push_back(i);long long best=1000000000;do{int cur=0;long long cost=0;bool ok=true;for(int u:p){if(c[cur][u]<0){ok=false;break;}cost+=c[cur][u];cur=u;}if(ok&&c[cur][0]>=0)best=min(best,cost+c[cur][0]);}while(next_permutation(p.begin(),p.end()));assert(shortestTour(c)==(best==1000000000?-1:best));}}`,

 'tree-traversal':()=>get('tree-traversal')+`\nvoid test(){vector<Node>example={{'A',1,2},{'B',-1,-1},{'C',-1,-1}};string p,i,o;preorder(0,example,p);inorder(0,example,i);postorder(0,example,o);assert(p=="ABC"&&i=="BAC"&&o=="BCA"&&levelOrder(0,example)==vector<char>({'A','B','C'}));vector<Node>t={{'A',1,2},{'B',3,-1},{'C',-1,-1},{'D',-1,-1}};string a,b,c;preorder(0,t,a);inorder(0,t,b);postorder(0,t,c);assert(a=="ABDC"&&b=="DBAC"&&c=="DBCA");assert(levelOrder(0,t)==vector<char>({'A','B','C','D'}));}`,
 'array-rotation':()=>get('array-rotation')+'\nvoid test(){vector<int>a={1,2,3,4,5};rotateLeft(a,7);assert(a==vector<int>({3,4,5,1,2}));assert(rotateClockwise({{1,2,3},{4,5,6}})==vector<vector<int>>({{4,1},{5,2},{6,3}}));}',
 'segment-tree':()=>get('segment-tree')+`\nvoid test(){vector<long long>ex={2,1,4,3};SegTree st(ex);assert(st.sum(1,4,1,0,4)==8);ex[2]=7;st.setValue(2,7,1,0,4);assert(st.sum(1,4,1,0,4)==11);mt19937 rng(99);for(int n=1;n<40;++n){vector<long long>a(n);SegTree t(a);for(int z=0;z<80;++z){int i=rng()%n;a[i]=int(rng()%101)-50;t.setValue(i,a[i],1,0,n);int l=rng()%n,r=l+1+rng()%(n-l);assert(t.sum(l,r,1,0,n)==accumulate(a.begin()+l,a.begin()+r,0LL));}}}`,
 'lca':()=>get('lca')+`\nvoid test(){mt19937 rng(193);for(int n=1;n<50;++n){LCA t(n);for(int i=1;i<n;++i){int p=rng()%i;t.adj[i].push_back(p);t.adj[p].push_back(i);}for(int root: {0,n-1}){t.build(root);vector<int>p(n,-1),dep(n);queue<int>q;q.push(root);p[root]=root;while(!q.empty()){int v=q.front();q.pop();for(int u:t.adj[v])if(p[u]==-1){p[u]=v;dep[u]=dep[v]+1;q.push(u);}}for(int i=0;i<n;++i)for(int j=0;j<n;++j){int a=i,b=j;while(dep[a]>dep[b])a=p[a];while(dep[b]>dep[a])b=p[b];while(a!=b){a=p[a];b=p[b];}assert(t.query(i,j)==a);}}}}`,

 'bitmask-subsets':()=> 'void test(){'+get('bitmask-subsets')+'\nint exampleMask=0b01010;assert((exampleMask&(1<<1))&&(exampleMask&(1<<3))&&!(exampleMask&(1<<0))&&!(exampleMask&(1<<2))&&!(exampleMask&(1<<4)));assert(dp.back()==0&&has&&mask==0);}',
 'lis':()=>get('lis')+`\nvoid test(){assert(lisOne({})==vector<int>{});auto ex=lisOne({10,20,10,30,20,50});assert(ex.size()==4&&ex==vector<int>({10,20,30,50}));mt19937 rng(31);for(int z=0;z<120;++z){int n=1+rng()%15;vector<int>a(n),d(n,1);for(auto&x:a)x=int(rng()%21)-10;int best=0;for(int i=0;i<n;++i){for(int j=0;j<i;++j)if(a[j]<a[i])d[i]=max(d[i],d[j]+1);best=max(best,d[i]);}auto b=lisOne(a);assert((int)b.size()==best);for(int i=1;i<(int)b.size();++i)assert(b[i-1]<b[i]);int j=0;for(int x:a)if(j<(int)b.size()&&x==b[j])++j;assert(j==(int)b.size());}}`,
 'sweep-line':()=>get('sweep-line')+'\nvoid test(){assert(maxOverlap({{1,4},{2,5},{4,7}})==2);assert(maxOverlap({{0,2},{2,4}})==1);assert(maxOverlap({{0,5},{1,3},{2,7}})==3);assert(maxOverlap({})==0);}',
 'monotonic-stack':()=>get('monotonic-stack')+`\nvoid test(){assert(nextGreater({2,1,2,4,3})==vector<int>({4,2,4,-1,-1}));mt19937 rng(81);for(int z=0;z<80;++z){vector<int>a(1+rng()%20);for(auto&x:a)x=rng()%10;auto b=nextGreater(a);for(int i=0;i<(int)a.size();++i){int want=-1;for(int j=i+1;j<(int)a.size();++j)if(a[j]>a[i]){want=a[j];break;}assert(b[i]==want);}}}`,
 'simulation-phases':()=>get('simulation-phases')+'\nvoid test(){assert(step({{10,0}})==vector<vector<int>>({{0,10}}));assert(step({{7}})==vector<vector<int>>({{7}}));}',
 'modular-math':()=>get('modular-math')+'\nvoid test(){assert(modPow(3,13,7)==3);assert(modPow(2,10,1000)==24);assert(modPow(-2,3,7)==6);assert(modPow(5,0,1)==0);assert(modPow(1000000006,2,1000000007)==1);}',
 'fenwick-tree':()=>get('fenwick-tree')+`\nvoid test(){Fenwick sample(4);vector<long long>ex={2,1,4,3};for(int i=0;i<4;++i)sample.add(i,ex[i]);sample.add(2,5);assert(sample.rangeSum(1,4)==13);mt19937 rng(46);Fenwick f(40);vector<long long>a(40);for(int z=0;z<200;++z){int i=rng()%40,v=int(rng()%101)-50;f.add(i,v);a[i]+=v;int l=rng()%41,r=l+rng()%(41-l);assert(f.rangeSum(l,r)==accumulate(a.begin()+l,a.begin()+r,0LL));}}`,
 'lcs':()=>get('lcs')+'\nvoid test(){assert(lcsLength("ABCBDAB","BDCABA")==4);assert(lcsLength("","a")==0);assert(lcsLength("abc","abc")==3);}',
 'cpp-essentials':()=>{let c=get('cpp-essentials'),i=c.indexOf('void process'),j=c.indexOf('int n; string line;');return c.slice(i,j)+'\nvoid test(){'+c.slice(0,i).replace('vector<Item> a;','vector<Item> a={{2,9},{2,3},{1,1}};')+c.slice(j)+'\nassert(n==4&&line=="hello world"&&product==12&&a[0].id==3);}';}
});
let cpp='#include <bits/stdc++.h>\nusing namespace std;\n';
for(const [id,make]of Object.entries(snippets))cpp+='namespace study_'+id.replaceAll('-','_')+'{\n'+make()+'\n}\n';
cpp+='int main(){'+Object.keys(snippets).map(id=>'study_'+id.replaceAll('-','_')+'::test();').join('')+'}\n';
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'algobook-study-'));
try{fs.writeFileSync(tmp+'/test.cpp',cpp);cp.execFileSync('g++',['-std=c++17','-O2',tmp+'/test.cpp','-o',tmp+'/test'],{stdio:'inherit'});cp.execFileSync(tmp+'/test',[],{stdio:['pipe','inherit','inherit'],input:'4\nhello world\n'});}finally{fs.rmSync(tmp,{recursive:true,force:true});}
console.log(JSON.stringify({studySnippets:Object.keys(snippets).length,randomizedOracles:12,status:'passed'}));
