// Compile the displayed study snippets, then compare key designs to slow independent oracles.
const fs=require('node:fs'),cp=require('node:child_process'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const cs=window.CHAPTERS, get=id=>cs.find(c=>c.id===id).code;
const snippets={
 'stl-performance':()=>{const s=get('stl-performance').split('// Dijkstra')[0];return s+'\nvoid test(){assert(kthLargest({4,9,9,1},2)==9);assert(kthLargest({-3},1)==-3);}';},
 'grid-search':()=>get('grid-search')+'\nvoid test(){assert(shortestPath({"1110","0101","1111"},0,0,2,3)==5);assert(shortestPath({"1"},0,0,0,0)==0);assert(shortestPath({"0"},0,0,0,0)==-1);assert(shortestPath({"10","01"},0,0,1,1)==-1);}',
 'graph-model':()=> 'void test(){int n=3,u=0,v=2,start=0;long long w=4;'+get('graph-model')+'\nassert(seen[2]&&!seen[1]);}',
 'shortest-variants':()=>{const [decl,loop]=get('shortest-variants').split('// Floyd-Warshall core:');return decl+'\nvoid test(){vector<long long> d;vector<Edge> e={{0,1,4},{0,2,5},{1,2,-3}};assert(bellmanFord(3,0,e,d)&&d[2]==1);e.push_back({2,1,1});assert(!bellmanFord(3,0,e,d));int n=4;vector<vector<long long>> dist(n,vector<long long>(n,INF));for(int i=0;i<n;++i)dist[i][i]=0;dist[0][1]=2;dist[1][2]=1;dist[2][3]=1;'+loop.slice(loop.indexOf('\n'))+'\nassert(dist[0][3]==4&&dist[3][0]==INF);}';},
 'sqrt-decomposition':()=>get('sqrt-decomposition')+`\nvoid test(){mt19937 rng(51);for(int n=1;n<60;++n){vector<long long>a(n);for(auto&x:a)x=int(rng()%101)-50;SqrtMax s(a);for(int z=0;z<80;++z){int i=rng()%n;a[i]=int(rng()%101)-50;s.update(i,a[i]);int l=rng()%n,r=l+1+rng()%(n-l);assert(s.query(l,r)==*max_element(a.begin()+l,a.begin()+r));}}}`,
 'mst':()=>get('mst')+'\nvoid test(){auto a=kruskal(4,{{0,1,1},{1,2,2},{2,3,3},{0,3,20}});assert(a.first==6&&a.second==3);assert(kruskal(4,{{0,1,1}}).second==1);}',
 'api-design':()=>get('api-design')+'\nvoid test(){Records r;r.init();r.add(900000001);assert(r.contains(900000001));assert(!r.remove(8)&&r.index.size()==1);assert(r.remove(900000001));r.add(900000001);assert(r.data.size()==2);r.init();assert(!r.contains(900000001));}',
 'number-editor':()=>get('number-editor')+`\nvoid test(){mt19937 rng(71);NumberEditor e;string a="12121",b="21122";e.init(a,b);assert(e.countNum(121)==3);for(int z=0;z<150;++z){string x,y;for(int i=0,n=1+rng()%4;i<n;++i)x+=char('1'+rng()%9);for(int i=0,n=1+rng()%4;i<n;++i)y+=char('1'+rng()%9);int dir=rng()%2;e.append(dir,stoi(x),stoi(y));if(dir){a+=x;b+=y;}else{a=x+a;b=y+b;}array<int,1000>cnt{};string all=a+b;for(int i=0;i+2<(int)all.size();++i)++cnt[stoi(all.substr(i,3))];for(int k=111;k<1000;++k)assert(e.countNum(k)==cnt[k]);}e.init("123","456");assert(e.countNum(234)==1);}`,
 'tile-index':()=>get('tile-index')+'\nvoid test(){assert(shapeKey({1,2,3,4,5})!=shapeKey({5,4,3,2,1}));TileOccupancy t(9);assert(t.place(1,0,0));assert(!t.place(2,2,2));assert(t.place(3,4,4));t.remove(1);assert(t.place(2,2,0));t.remove(999);}',
 'freight':()=>get('freight')+`\nvoid test(){mt19937 rng(17);for(int z=0;z<80;++z){int n=2+rng()%7;vector<vector<pair<int,int>>>adj(n);vector<vector<int>>d(n,vector<int>(n));for(int i=0;i<n;++i){d[i][i]=INT_MAX;for(int j=0;j<n;++j)if(i!=j&&rng()%3==0){int w=1+rng()%50;adj[i].push_back({j,w});d[i][j]=w;}}for(int k=0;k<n;++k)for(int i=0;i<n;++i)for(int j=0;j<n;++j)d[i][j]=max(d[i][j],min(d[i][k],d[k][j]));for(int i=0;i<n;++i)for(int j=0;j<n;++j)assert(widest(adj,i,j)==d[i][j]);}}`,
 'road-failure':()=>get('road-failure')+`\nvoid test(){assert(maxDelay(4,{{0,1,2},{1,3,2},{0,2,3},{2,3,3}},0,3)==2);assert(maxDelay(2,{{0,1,2}},0,1)==-1);mt19937 rng(97);for(int z=0;z<80;++z){int n=2+rng()%6;vector<Road>e;for(int i=0;i<n;++i)for(int j=0;j<n;++j)if(i!=j&&rng()%3==0)e.push_back({i,j,(long long)(1+rng()%15),rng()%5!=0});auto floyd=[&](int ban){vector<vector<long long>>d(n,vector<long long>(n,1000000000));for(int i=0;i<n;++i)d[i][i]=0;for(int i=0;i<(int)e.size();++i)if(i!=ban&&e[i].alive)d[e[i].from][e[i].to]=min(d[e[i].from][e[i].to],e[i].time);for(int k=0;k<n;++k)for(int i=0;i<n;++i)for(int j=0;j<n;++j)d[i][j]=min(d[i][j],d[i][k]+d[k][j]);return d[0][n-1];};long long base=floyd(-1),want=0;if(base==1000000000)want=-1;else for(int i=0;i<(int)e.size();++i)if(e[i].alive){long long d=floyd(i);if(d==1000000000){want=-1;break;}want=max(want,d-base);}assert(maxDelay(n,e,0,n-1)==want);}}`,
 'ev-route':()=>get('ev-route')+'\nvoid test(){vector<vector<EVRoad>>a={{{1,2,3}},{{2,2,2}}, {}};vector<int>c={1,2,1};assert(infectionTimes(a,{{0,7},{0,3},{1,10}})[2]==7);vector<long long>s={100,100,100};assert(safeTrip(a,c,s,3,0,2)==5);s[1]=3;assert(safeTrip(a,c,s,3,0,2)==-1);s={0,100,100};assert(safeTrip(a,c,s,3,0,2)==-1);s={100,100,5};assert(safeTrip(a,c,s,3,0,2)==-1);}',
 'energy-route':()=>get('energy-route')+`\nvoid test(){assert(attrCost(encode("PWD"),encode("PWD"))==1);assert(attrCost(encode("DPP"),encode("PPD"))==2);assert(energyCost(3,{{0,1},{1,2}},{encode("PWD"),encode("WPD")},{true,true},0,2,encode("PWD"))==2);assert(energyCost(3,{{0,1},{1,2}},{encode("PWD"),encode("WPD")},{true,false},0,2,encode("PWD"))==-1);mt19937 rng(79);for(int z=0;z<80;++z){int n=4,m=5;vector<pair<int,int>>ends;vector<Attr>p;vector<bool>alive(m,true);for(int i=0;i<m;++i){int a=rng()%n,b=rng()%n;ends.push_back({a,b});string s(6,'P');for(auto&c:s)c=(rng()%2?'P':'W');s[rng()%6]='D';p.push_back(encode(s));}Attr init=encode("PWDPWP");int best=1000000;vector<vector<int>>d(n,vector<int>(m+1,1000000));d[0][0]=0;vector<Attr>attr={init};attr.insert(attr.end(),p.begin(),p.end());auto cost=[](Attr a,Attr b){int c=0;for(int i=0;i<6;++i)c+=(i==a.d||i==b.d||((a.w>>i&1)!=(b.w>>i&1)));return c;};for(int it=0;it<n*(m+1);++it)for(int i=0;i<m;++i)for(int dir=0;dir<2;++dir){int a=dir?ends[i].second:ends[i].first,b=dir?ends[i].first:ends[i].second;for(int k=0;k<=m;++k)if(d[a][k]<1000000){d[b][k]=min(d[b][k],d[a][k]+cost(attr[k],p[i]));if(k==0)d[b][i+1]=min(d[b][i+1],d[a][0]+1);}}best=*min_element(d[n-1].begin(),d[n-1].end());assert(energyCost(n,ends,p,alive,0,n-1,init)==(best==1000000?-1:best));}}`,
 'parkingcase':()=>get('parkingcase')+'\nvoid test(){cars={{0,0,0,200,1234,0,"02A1234"},{0,1,0,100,1234,0,"01A1234"}};bySuffix[1234]={{0,200,0},{0,100,1}};vector<priority_queue<int,vector<int>,greater<int>>>slots(1);assert(topCars(1234,5)==vector<int>({1,0}));tow(1,slots);assert(topCars(1234,5)==vector<int>({0,1}));assert(slots[0].top()==1);tow(1,slots);assert(slots[0].size()==1);}',
 'loginqueuecase':()=>get('loginqueuecase')+'\nvoid test(){serverBuckets.resize(2);serverCount={2,1};users={{0,true},{0,true},{1,true}};buckets.resize(2);allWaiting={0,1};serverBuckets[0]={0};serverBuckets[1]={1};buckets[0]={0,2,true,{0,1},allWaiting.begin(),serverBuckets[0].begin()};buckets[1]={1,1,true,{2},next(allWaiting.begin()),serverBuckets[1].begin()};moveServerBucketsToBack(0);assert(vector<int>(allWaiting.begin(),allWaiting.end())==vector<int>({1,0}));cancelUser(0);assert(!isWaiting(0)&&buckets[0].liveCount==1&&serverCount[0]==1);cancelUser(0);assert(serverCount[0]==1);buckets[0].active=false;assert(!isWaiting(1));}',
 'dictionarycase':()=>get('dictionarycase')+`\nvoid test(){set<string>s;mt19937 rng(123);for(int z=0;z<120;++z){string w;for(int i=0,n=1+rng()%5;i<n;++i)w+=char('a'+rng()%4);if(!s.count(w)){s.insert(w);addWord(w);bucketAdd(w);}int i=0;for(auto&t:s){assert(kthWord(++i)==t);assert(oneBasedRank(t)==i);assert(pageOf(t,3)==(i-1)/3+1);}if(z%3==0&&!s.empty()){w=*s.begin();removeWord(w);bucketRemove(w);s.erase(w);}}int i=0;for(auto&t:s)assert(kthWord(++i)==t);}`
};
Object.assign(snippets,{
 'dp-patterns':()=>get('dp-patterns')+`\nvoid test(){assert(knapsack01({2,3},{4,5},4)==5);assert(shortestTour({{0}})==0);assert(shortestTour({{-1,1,-1},{-1,-1,1},{1,-1,-1}})==3);mt19937 rng(65);for(int z=0;z<50;++z){int n=2+rng()%6;vector<vector<int>>c(n,vector<int>(n,-1));for(int i=0;i<n;++i)for(int j=0;j<n;++j)if(i!=j&&rng()%4)c[i][j]=rng()%20;vector<int>p;for(int i=1;i<n;++i)p.push_back(i);long long best=1000000000;do{int cur=0;long long cost=0;bool ok=true;for(int u:p){if(c[cur][u]<0){ok=false;break;}cost+=c[cur][u];cur=u;}if(ok&&c[cur][0]>=0)best=min(best,cost+c[cur][0]);}while(next_permutation(p.begin(),p.end()));assert(shortestTour(c)==(best==1000000000?-1:best));}}`,

 'tree-traversal':()=>get('tree-traversal')+`\nvoid test(){vector<Node>t={{'A',1,2},{'B',3,-1},{'C',-1,-1},{'D',-1,-1}};string a,b,c;preorder(0,t,a);inorder(0,t,b);postorder(0,t,c);assert(a=="ABDC"&&b=="DBAC"&&c=="DBCA");assert(levelOrder(0,t)==vector<char>({'A','B','C','D'}));}`, 
 'array-rotation':()=>get('array-rotation')+'\nvoid test(){vector<int>a={1,2,3,4,5};rotateLeft(a,7);assert(a==vector<int>({3,4,5,1,2}));assert(rotateClockwise({{1,2,3},{4,5,6}})==vector<vector<int>>({{4,1},{5,2},{6,3}}));}',
 'segment-tree':()=>get('segment-tree')+`\nvoid test(){mt19937 rng(99);for(int n=1;n<40;++n){vector<long long>a(n);SegTree t(a);for(int z=0;z<80;++z){int i=rng()%n;a[i]=int(rng()%101)-50;t.setValue(i,a[i],1,0,n);int l=rng()%n,r=l+1+rng()%(n-l);assert(t.sum(l,r,1,0,n)==accumulate(a.begin()+l,a.begin()+r,0LL));}}}`,
 'lca':()=>get('lca')+`\nvoid test(){mt19937 rng(193);for(int n=1;n<50;++n){LCA t(n);for(int i=1;i<n;++i){int p=rng()%i;t.adj[i].push_back(p);t.adj[p].push_back(i);}for(int root: {0,n-1}){t.build(root);vector<int>p(n,-1),dep(n);queue<int>q;q.push(root);p[root]=root;while(!q.empty()){int v=q.front();q.pop();for(int u:t.adj[v])if(p[u]==-1){p[u]=v;dep[u]=dep[v]+1;q.push(u);}}for(int i=0;i<n;++i)for(int j=0;j<n;++j){int a=i,b=j;while(dep[a]>dep[b])a=p[a];while(dep[b]>dep[a])b=p[b];while(a!=b){a=p[a];b=p[b];}assert(t.query(i,j)==a);}}}}`,

 'bitmask-subsets':()=> 'void test(){'+get('bitmask-subsets')+'\nassert(dp.back()==0&&has&&mask==0);}',
 'lis':()=>get('lis')+`\nvoid test(){assert(lisOne({}).empty());mt19937 rng(31);for(int z=0;z<120;++z){int n=1+rng()%15;vector<int>a(n),d(n,1);for(auto&x:a)x=int(rng()%21)-10;int best=0;for(int i=0;i<n;++i){for(int j=0;j<i;++j)if(a[j]<a[i])d[i]=max(d[i],d[j]+1);best=max(best,d[i]);}auto b=lisOne(a);assert((int)b.size()==best);for(int i=1;i<(int)b.size();++i)assert(b[i-1]<b[i]);int j=0;for(int x:a)if(j<(int)b.size()&&x==b[j])++j;assert(j==(int)b.size());}}`,
 'sweep-line':()=>get('sweep-line')+'\nvoid test(){assert(maxOverlap({{0,2},{2,4}})==1);assert(maxOverlap({{0,5},{1,3},{2,7}})==3);assert(maxOverlap({})==0);}',
 'monotonic-stack':()=>get('monotonic-stack')+`\nvoid test(){mt19937 rng(81);for(int z=0;z<80;++z){vector<int>a(1+rng()%20);for(auto&x:a)x=rng()%10;auto b=nextGreater(a);for(int i=0;i<(int)a.size();++i){int want=-1;for(int j=i+1;j<(int)a.size();++j)if(a[j]>a[i]){want=a[j];break;}assert(b[i]==want);}}}`,
 'simulation-phases':()=>get('simulation-phases')+'\nvoid test(){assert(step({{10,0}})==vector<vector<int>>({{0,10}}));assert(step({{7}})==vector<vector<int>>({{7}}));}',
 'modular-math':()=>get('modular-math')+'\nvoid test(){assert(modPow(2,10,1000)==24);assert(modPow(-2,3,7)==6);assert(modPow(5,0,1)==0);assert(modPow(1000000006,2,1000000007)==1);}',
 'fenwick-tree':()=>get('fenwick-tree')+`\nvoid test(){mt19937 rng(46);Fenwick f(40);vector<long long>a(40);for(int z=0;z<200;++z){int i=rng()%40,v=int(rng()%101)-50;f.add(i,v);a[i]+=v;int l=rng()%41,r=l+rng()%(41-l);assert(f.rangeSum(l,r)==accumulate(a.begin()+l,a.begin()+r,0LL));}}`,
 'lcs':()=>get('lcs')+'\nvoid test(){assert(lcsLength("ABCBDAB","BDCABA")==4);assert(lcsLength("","a")==0);assert(lcsLength("abc","abc")==3);}',
 'cpp-essentials':()=>{let c=get('cpp-essentials'),i=c.indexOf('void process'),j=c.indexOf('int n; string line;');return c.slice(i,j)+'\nvoid test(){'+c.slice(0,i).replace('vector<Item> a;','vector<Item> a={{2,9},{2,3},{1,1}};')+c.slice(j)+'\nassert(n==4&&line=="hello world"&&product==12&&a[0].id==3);}';}
});
let cpp='#include <bits/stdc++.h>\nusing namespace std;\n';
for(const [id,make]of Object.entries(snippets))cpp+='namespace study_'+id.replaceAll('-','_')+'{\n'+make()+'\n}\n';
cpp+='int main(){'+Object.keys(snippets).map(id=>'study_'+id.replaceAll('-','_')+'::test();').join('')+'}\n';
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'algobook-study-'));
try{fs.writeFileSync(tmp+'/test.cpp',cpp);cp.execFileSync('g++',['-std=c++17','-O2',tmp+'/test.cpp','-o',tmp+'/test'],{stdio:'inherit'});cp.execFileSync(tmp+'/test',[],{stdio:['pipe','inherit','inherit'],input:'4\nhello world\n'});}finally{fs.rmSync(tmp,{recursive:true,force:true});}
console.log(JSON.stringify({studySnippets:Object.keys(snippets).length,randomizedOracles:12,status:'passed'}));
